# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27fd94578dc514036f11344c032c1de2d8f1280283ed054804cba543204e7cfb93d23ac30cce743e57a667b58dac8c1867a9a22dc093c065c1c704369e84459d

test:
  secret_key_base: dd282c121985dd9c0c23e39d5df1c15a42ee04cb65bb22bff0d1a382f4c480fc27d7f65d0ea6202b8cfe056f8279c986e07be9f275fd0f956d930c0a8d27762b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
